spring:
  datasource:
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      url: "jdbc:mysql://127.0.0.1:3307/test"
      username: "root"
      password: "1234"

  jpa:
    show-sql: true
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      #      db 변경 사항 적용 -> 향후 none
      ddl-auto: update
