server:
  port: 8080

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3307/test"
    username: "root"
    password: "1234"
  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        ddl-auto: update


#twilio:
#  credentials:
#    TWILIO_ACCOUNT_SID: ACed602bb1cc232f332a34ec5849fa4ec8
#    TWILIO_AUTH_TOKEN: 6082dd82e4455d82f3f06e9679304fd5
#    TWILIO_OUTGOING_SMS_NUMBER: +19896238055
